# (c) 2022 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# This AWS Content is provided subject to the terms of the AWS Customer
# Agreement available at https://aws.amazon.com/agreement or other written
# agreement between Customer and Amazon Web Services, Inc.

###############################################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: Provision an encryption key to be used by AWS Control Tower landing zone components.

Resources:
  LZKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key used by Control Tower Landing Zone components
      EnableKeyRotation: true
      KeySpec: SYMMETRIC_DEFAULT
      PendingWindowInDays: 30
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: Allow CloudTrail to encrypt/decrypt logs
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action:
              - kms:Decrypt*
              - kms:GenerateDataKey*
            Resource: "*"
          - Sid: Allow Config to encrypt/decrypt logs
            Effect: Allow
            Principal:
              Service: "config.amazonaws.com"
            Action:
              - kms:Decrypt*
              - kms:GenerateDataKey*
            Resource: "*"
          - Sid: Enable encrypted CloudWatch Logs
            Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: "*"
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Sid: Allow Budgets to publish on encrypted SNS topic
            Effect: Allow
            Principal:
              Service: "budgets.amazonaws.com"
            Action:
              - kms:Decrypt*
              - kms:GenerateDataKey*
            Resource: "*"

  LZKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/ControlTowerSetup-Landing-Zone
      TargetKeyId: !Ref LZKmsKey

Outputs:
  LZKeyARN:
    Description: ARN of KMS Key used to encrypt LZ components
    Value: !GetAtt LZKmsKey.Arn
    Export:
      Name: LandingZoneKeyARN
  LZKeyId:
    Description: KeyId of KMS Key used to encrypt LZ components
    Value: !Ref LZKmsKey
    Export:
      Name: LandingZoneKeyId
  LZKeyAlias:
    Description: KMS Key used to encrypt LZ components
    Value: !Ref LZKmsKeyAlias
    Export:
      Name: LandingZoneKeyAlias
